services:
  app:
    image: herolock:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:dev
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/app
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'herolock'
      MYSQL_ROOT_PASSWORD: 'root' 
